<?php

namespace App\Models\Explorer;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

/**
 * App\Models\Explorer\ProjectColumnComment
 *
 * @property        int                                                        $id
 * @property        int                                                        $project_id
 * @property        string                                                     $user_id
 * @property        string|null                                                $comment_text
 * @property        string                                                     $table_name
 * @property        string                                                     $column_name
 * @property        bool|null                                                  $is_auto_generated
 * @property        bool|null                                                  $is_deleted
 * @property        \Illuminate\Support\Carbon|null                            $created_at
 * @property        \Illuminate\Support\Carbon|null                            $updated_at
 * @property        string|null                                                $schema_name
 * @property        \Illuminate\Support\Carbon|null                            $deleted_at
 * @method   static \Illuminate\Database\Eloquent\Builder|ProjectColumnComment newModelQuery()
 * @method   static \Illuminate\Database\Eloquent\Builder|ProjectColumnComment newQuery()
 * @method   static \Illuminate\Database\Query\Builder|ProjectColumnComment    onlyTrashed()
 * @method   static \Illuminate\Database\Eloquent\Builder|ProjectColumnComment query()
 * @method   static \Illuminate\Database\Eloquent\Builder|ProjectColumnComment whereColumnName($value)
 * @method   static \Illuminate\Database\Eloquent\Builder|ProjectColumnComment whereCommentText($value)
 * @method   static \Illuminate\Database\Eloquent\Builder|ProjectColumnComment whereCreatedAt($value)
 * @method   static \Illuminate\Database\Eloquent\Builder|ProjectColumnComment whereDeletedAt($value)
 * @method   static \Illuminate\Database\Eloquent\Builder|ProjectColumnComment whereId($value)
 * @method   static \Illuminate\Database\Eloquent\Builder|ProjectColumnComment whereIsAutoGenerated($value)
 * @method   static \Illuminate\Database\Eloquent\Builder|ProjectColumnComment whereIsDeleted($value)
 * @method   static \Illuminate\Database\Eloquent\Builder|ProjectColumnComment whereProjectId($value)
 * @method   static \Illuminate\Database\Eloquent\Builder|ProjectColumnComment whereSchemaName($value)
 * @method   static \Illuminate\Database\Eloquent\Builder|ProjectColumnComment whereTableName($value)
 * @method   static \Illuminate\Database\Eloquent\Builder|ProjectColumnComment whereUpdatedAt($value)
 * @method   static \Illuminate\Database\Eloquent\Builder|ProjectColumnComment whereUserId($value)
 * @method   static \Illuminate\Database\Query\Builder|ProjectColumnComment    withTrashed()
 * @method   static \Illuminate\Database\Query\Builder|ProjectColumnComment    withoutTrashed()
 * @mixin \Eloquent
 */
class ProjectColumnComment extends Model
{
    use HasFactory, SoftDeletes;

    protected $guarded = ['id'];

    protected $table = 'bp_project_column_comments';
}
